---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_version: <%= ENV['KITCHEN_CHEF_VER'] || 14 %>

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[pleroma_test_cookbook::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
